"""Pydantic schema for the Auditor agent structured output."""

from pydantic import BaseModel, Field, field_validator
from typing import Optional

class AuditorOutput(BaseModel):    
    """
    Schema for the output generated by the Auditor agent.
    
    This model defines the structured format for the clinical audit report, 
    including protocol references, risk categories, score verification, 
    evidence citations, suggestions, reasoning, and potential warnings.
    """
    protocol_reference: str = Field(
        ..., 
        description="Exact name of the protocol used as base (ex: NEWS2, Sepsis-3, Manchester)."
    )
    
    clinical_risk_category: str = Field(
        ...,
        description="""
            Standardized risk category: 'Low Risk', 'Medium Risk / Monitor',
            'High Risk / Emergency', or 'Critical / Resuscitation'.
        """
    )

    @field_validator("clinical_risk_category")
    @classmethod
    def normalize_risk_category(cls, v: str) -> str:
        """Normalize risk category to canonical values, tolerating LLM output variations."""
        mapping = {
            "low": "Low Risk",
            "medium": "Medium Risk / Monitor",
            "monitor": "Medium Risk / Monitor",
            "high": "High Risk / Emergency",
            "emergency": "High Risk / Emergency",
            "critical": "Critical / Resuscitation",
            "resuscitation": "Critical / Resuscitation",
        }
        v_lower = v.strip().lower()
        for key, canonical in mapping.items():
            if key in v_lower:
                return canonical
        return v
    
    calculated_score_audit: str = Field(
        ...,
        description="Text confirmation of received score (e.g.: 'NEWS2 Score of 5 verified')."
    )
    
    evidence_quote: str = Field(
        ...,
        description="""
            Direct and exact citation of the text retrieved by RAG that
            justifies the suggested conduct.
        """
    )
    
    clinical_suggestion: str = Field(
        ...,
        description="Recommendation of immediate action for the medical/nursing team, concise and direct."
    )
    
    reasoning_trace: str = Field(
        ...,
        description="Chain of Thought resumed: Data + Rule = Conclusion."
    )

    missing_info_warning: Optional[str] = Field(
        None,
        description="""
            Warning about crucial data that were absent on original input 
            (e.g.: 'Lactate not reported.').
        """
    )