from typing import List, Optional, Literal
from pydantic import BaseModel, Field, field_validator

# --- Enums para Restrição de Output ---
# Isso impede que o modelo invente status como "Semi-Conscious"
TypeAdmissionType = Literal['EMERGENCY', 'URGENT', 'ELECTIVE']
TypeService = Literal['MEDICINE', 'SURGERY', 'ORTHOPEDICS', 'NEUROLOGY', 'PSYCHIATRY', 'OTHER']
TypeAVPU = Literal['Alert', 'Voice', 'Pain', 'Unresponsive']
TypeACVPU = Literal['Alert', 'Confusion', 'Voice', 'Pain', 'Unresponsive']
TypeChange = Literal['NEW_START', 'DOSE_INCREASE', 'DOSE_DECREASE', 'STOPPED', 'UNCHANGED']

# --- Schemas de Output ---

class MetadataSchema(BaseModel):
    """
    Schema for administrative metadata captured during the triage or admission process.
    
    Attributes:
        admission_type (TypeAdmissionType, optional): The urgency/category of the admission (EMERGENCY, URGENT, ELECTIVE).
        service (TypeService, optional): The primary medical specialty service responsible for the patient.
        discharge_disposition (str, optional): The destination or status of the patient upon discharge (e.g., 'Home', 'Expired').
    """
    admission_type: Optional[TypeAdmissionType] = Field(None, description="The urgency level of admission.")
    service: Optional[TypeService] = Field(None, description="Primary medical service.")
    discharge_disposition: Optional[str] = Field(None, description="Final disposition (e.g., 'Home', 'SNF', 'Expired').")

class SemanticSchema(BaseModel):
    """
    Schema for high-level semantic understanding and summarization of the patient's visit.
    
    Attributes:
        summary (str, optional): A concise clinical narrative summarizing the patient's presentation and course.
        key_conditions (List[str]): Extracted diagnoses, comorbidities, or acute problems managed during the visit.
        chief_complaint (str, optional): The primary reason for the visit or the main symptom reported by the patient.
    """
    summary: Optional[str] = Field(None, description="Concise 2-3 sentence clinical summary of the patient's course.")
    key_conditions: List[str] = Field(default_factory=list, description="List of active diagnoses and comorbidities managed.")
    chief_complaint: Optional[str] = Field(None, description="Primary symptom prompting the ED visit.")

    @field_validator("summary")
    def check_summary_length(cls: BaseModel, v: str) -> str:
        """
        Validates that the generated summary does not exceed the token/word limit to ensure conciseness.
        
        Args:
            v (str): The summary text generated by the previous model step.
            
        Raises:
            ValueError: If the summary contains more than 300 words, indicating it has failed the 'conciseness' constraint.
            
        Returns:
            str: The validated summary text.
        """
        if v is not None and len(v.split()) > 300:
            raise ValueError("summary must be concise (under ~100 words)")
        return v

class VitalsSchema(BaseModel):
    """
    Schema for structured vital signs data extracted from triage or admission notes.
    Fields should be None if the value is not explicitly stated in the source text.
    
    Attributes:
        temperature (float, optional): Body temperature in Celsius.
        heartrate (int, optional): Heart rate in beats per minute (BPM).
        resprate (int, optional): Respiratory rate in breaths per minute (RPM).
        o2sat (int, optional): Oxygen saturation percentage (SpO2).
        sbp (int, optional): Systolic blood pressure in mmHg.
        dbp (int, optional): Diastolic blood pressure in mmHg.
        pain (int, optional): Pain score on a scale of 0-10.
        acuity (int, optional): Triage acuity level (e.g., ESI 1-5).
        supplemental_oxygen (bool, optional): Boolean flag indicating if the patient is on supplemental oxygen.
        gcs (int, optional): Glasgow Coma Scale score (3-15).
        avpu (TypeAVPU, optional): Consciousness level based on the AVPU scale (MEWS standard).
        acvpu (TypeACVPU, optional): Consciousness level based on the ACVPU scale (NEWS2 standard).
    """
    temperature: Optional[float] = Field(None, description="Temperature in Celsius. Convert from F if needed.")
    heartrate: Optional[int] = Field(None, description="Heart rate (BPM).")
    resprate: Optional[int] = Field(None, description="Respiratory rate (BPM).")
    o2sat: Optional[int] = Field(None, description="O2 Saturation (%) on admission.")
    sbp: Optional[int] = Field(None, description="Systolic BP (mmHg).")
    dbp: Optional[int] = Field(None, description="Diastolic BP (mmHg).")
    pain: Optional[int] = Field(None, description="Pain score (0-10).")
    acuity: Optional[int] = Field(None, description="ESI Acuity Level (1-5) if stated or clearly inferable.")
    supplemental_oxygen: Optional[bool] = Field(None, description="True if on O2, False if Room Air.")
    gcs: Optional[int] = Field(None, description="Escala de Coma de Glasgow (3-15)")
    avpu: Optional[TypeAVPU] = Field(None, description="Level of consciousness following MEWS standard. Use 'Alert' only if fully oriented")
    acvpu: Optional[TypeACVPU] = Field(
        None, 
        description="Level of consciousness following NEWS2 standard. Use 'Confusion' for new onset confusion, delirium, or disorientation. Use 'Alert' only if fully oriented."
    )

    @field_validator("temperature")
    def check_temperature(cls: BaseModel, v: float) -> float:
        """
        Validates the body temperature to ensure it falls within a biologically plausible range for humans (in Celsius).
        
        Range: 25.0°C (severe hypothermia) to 45.0°C (extreme hyperthermia/incompatible with life).
        Values outside this range likely indicate extraction error or unit mismatch (e.g., Fahrenheit).
        """
        if v is not None and not (25.0 <= v <= 45.0):
            raise ValueError("temperature must be between 25.0 and 45.0 Celsius")
        return v

    @field_validator("heartrate")
    def check_heartrate(cls: BaseModel, v: int) -> int:
        """
        Validates heart rate (BPM).
        
        Range: 0 (asystole) to 300 (extreme tachyarrhythmia limit).
        Filters out implausible values often caused by OCR or transcription errors.
        """
        if v is not None and not (0 <= v <= 300):
            raise ValueError("heartrate must be between 0 and 300 BPM")
        return v
    
    @field_validator("resprate")
    def check_resprate(cls: BaseModel, v: int) -> int:
        """
        Validates respiratory rate (breaths/min).
        
        Range: >0 to 60. 
        Values >60 are extremely rare in adults (even in severe distress) and usually indicate data entry error.
        """
        if v is not None and not (0 < v <= 60):
            raise ValueError("resprate must be between 0 and 60 RPM")
        return v
    
    @field_validator("o2sat")
    def check_o2sat(cls: BaseModel, v: int) -> int:
        """
        Validates peripheral Oxygen Saturation (SpO2).
        
        Range: 0% to 100%. 
        """
        if v is not None and not (0 <= v <= 100):
            raise ValueError("o2sat must be between 0 and 100 %")
        return v
    
    @field_validator("sbp")
    def check_sbp(cls: BaseModel, v: int) -> int:
        """
        Validates Systolic Blood Pressure (mmHg).
        
        Range: 10 to 400.
        Note: <50 is critical shock; >250 is hypertensive crisis. 
        Limits set to filter physically impossible values.
        """
        if v is not None and not (10 <= v <= 400):
            raise ValueError("sbp must be between 10 and 400 mmHg")
        return v

    @field_validator("dbp")
    def check_dbp(cls: BaseModel, v: int) -> int:
        """
        Validates Diastolic Blood Pressure (mmHg).
        
        Range: 10 to 300.
        """
        if v is not None and not (10 <= v <= 300):
            raise ValueError("dbp must be between 10 and 300 mmHg")
        return v
    
    @field_validator("pain")
    def check_pain(cls: BaseModel, v: int) -> int:
        """
        Validates the Numeric Pain Rating Scale (NPRS).
        
        Range: 0 (no pain) to 10 (worst pain imaginable).
        """
        if v is not None and not (0 <= v <= 10):
            raise ValueError("pain must be between 0 and 10")
        return v
    
    @field_validator("acuity")
    def check_acuity(cls: BaseModel, v: int) -> int:
        """
        Validates the Emergency Severity Index (ESI) level.
        
        Range: 1 (Most Urgent/Resuscitation) to 5 (Non-urgent).
        """
        if v is not None and not (1 <= v <= 5):
            raise ValueError("acuity must be between 1 and 5")
        return v


class LabsSchema(BaseModel):
    """
    Schema for key laboratory test results. 
    Focuses on critical values required for standard risk scores (MEWS, NEWS2, etc.).
    
    Attributes:
        potassium (float, optional): Serum Potassium level in mEq/L.
        sodium (float, optional): Serum Sodium level in mEq/L.
        creatinine (float, optional): Serum Creatinine level in mg/dL.
        wbc (float, optional): White Blood Cell count in K/uL.
        platelets (float, optional): Platelet count in K/uL.
        inr (float, optional): International Normalized Ratio (coagulation).
        albumin (float, optional): Serum Albumin in g/dL.
        bilirubin (float, optional): Total Bilirubin in mg/dL.
        ast (float, optional): Aspartate Aminotransferase level in U/L.
        alt (float, optional): Alanine Aminotransferase level in U/L.
    """
    potassium: Optional[float] = Field(None, description="K+ (mEq/L)")
    sodium: Optional[float] = Field(None, description="Na+ (mEq/L)")
    creatinine: Optional[float] = Field(None, description="Cr (mg/dL)")
    wbc: Optional[float] = Field(None, description="WBC count (K/uL)")
    platelets: Optional[float] = Field(None, description="Plt count (K/uL)")
    inr: Optional[float] = Field(None, description="INR")
    albumin: Optional[float] = Field(None, description="Albumin (g/dL)")
    bilirubin: Optional[float] = Field(None, description="Total Bilirubin (mg/dL)")
    ast: Optional[float] = Field(None, description="AST (U/L)")
    alt: Optional[float] = Field(None, description="ALT (U/L)")

    @field_validator("potassium")
    def check_potassium(cls: BaseModel, v: float) -> float:
        """
        Validates Potassium (K+) level.
        
        Range: 0.5 to 12.0 mEq/L.
        Note: <2.5 or >6.5 are critical values. The bounds are set to catch data entry errors (e.g., entering 40 instead of 4.0).
        """
        if v is not None and not (0.5 <= v <= 12.0):
            raise ValueError("potassium must be between 0.5 and 12.0 mEq/L")
        return v
    
    @field_validator("sodium")
    def check_sodium(cls: BaseModel, v: float) -> float:
        """
        Validates Sodium (Na+) level.
        
        Range: 80.0 to 200.0 mEq/L.
        Catches gross errors while allowing for severe hyponatremia (<120) or hypernatremia (>160).
        """
        if v is not None and not (80.0 <= v <= 200.0):
            raise ValueError("sodium must be between 80.0 and 200.0 mEq/L")
        return v
    
    @field_validator("creatinine")
    def check_creatinine(cls: BaseModel, v: float) -> float:
        """
        Validates Serum Creatinine (Cr).
        
        Range: 0.1 to 40.0 mg/dL.
        High values allowed for severe renal failure/dialysis patients.
        """
        if v is not None and not (0.1 <= v <= 40.0):
            raise ValueError("creatinine must be between 0.1 and 40.0 mg/dL")
        return v
    
    @field_validator("wbc")
    def check_wbc(cls: BaseModel, v: float) -> float:
        """
        Validates White Blood Cell count (WBC).
        
        Range: 0 to 500.0 K/uL.
        Upper limit accommodates extreme leukemoid reactions or leukemia.
        """
        if v is not None and not (0 <= v <= 500.0):
            raise ValueError("wbc must be between 0 and 500.0 K/uL")
        return v
    
    @field_validator("platelets")
    def check_platelets(cls: BaseModel, v: float) -> float:
        """
        Validates Platelet count.
        
        Range: 0 to 2000.0 K/uL.
        """
        if v is not None and not (0 <= v <= 2000.0):
            raise ValueError("platelets must be between 0 and 2000.0 K/uL")
        return v
    
    @field_validator("inr")
    def check_inr(cls: BaseModel, v: float) -> float:
        """
        Validates International Normalized Ratio (INR).
        
        Range: 0.5 to 30.0.
        Note: Normal is ~1.0. Therapeutic ~2-3.
        """
        if v is not None and not (0.5 <= v <= 30.0):
            raise ValueError("inr must be between 0.5 and 30.0")
        return v
    
    @field_validator("albumin")
    def check_albumin(cls: BaseModel, v: float) -> float:
        """
        Validates Serum Albumin.
        
        Range: 0.5 to 7.0 g/dL.
        """
        if v is not None and not (0.5 <= v <= 7.0):
            raise ValueError("albumin must be between 0.5 and 7.0 g/dL")
        return v
    
    @field_validator("bilirubin")
    def check_bilirubin(cls: BaseModel, v: float) -> float:
        """
        Validates Total Bilirubin.
        
        Range: 0.1 to 80.0 mg/dL.
        """
        if v is not None and not (0.1 <= v <= 80.0):
            raise ValueError("bilirubin must be between 0.1 and 80.0 mg/dL")
        return v
    
    @field_validator("ast")
    def check_ast(cls: BaseModel, v: int) -> int:
        """
        Validates Aspartate Aminotransferase (AST).
        
        Range: 0 to 20000 U/L.
        Allows for massive hepatic necrosis values.
        """
        if v is not None and not (0 <= v <= 20000):
            raise ValueError("ast must be between 0 and 20000 U/L")
        return v
    
    @field_validator("alt")
    def check_alt(cls: BaseModel, v: int) -> int:
        """
        Validates Alanine Aminotransferase (ALT).
        
        Range: 0 to 20000 U/L.
        """
        if v is not None and not (0 <= v <= 20000):
            raise ValueError("alt must be between 0 and 20000 U/L")
        return v
    

class FindingsSchema(BaseModel):
    """
    Schema for synthesizing structured physical examination findings.
    
    Attributes:
        abdomen (str, optional): Key findings from the abdominal exam (e.g., tenderness, distension).
        extremities (str, optional): Findings related to extremities (e.g., edema, pulse deficits).
        mental_status (str, optional): Narrative description of the patient's mental status or neurological state.
    """
    abdomen: Optional[str] = Field(None, description="Specific abdominal findings (e.g., 'distended', 'soft').")
    extremities: Optional[str] = Field(None, description="Edema, pulses, or perfusion findings.")
    mental_status: Optional[str] = Field(None, description="Detailed mental status exam notes.")

class ClinicalSchema(BaseModel):
    """
    Aggregated schema that bundles all objective clinical data (Vitals, Labs, Exam Findings).
    
    Attributes:
        vitals (VitalsSchema): Structured vital signs.
        labs (LabsSchema): Structured laboratory results.
        findings (FindingsSchema): Structured physical exam findings.
    """
    vitals: VitalsSchema = Field(..., description="Admission vital signs.")
    labs: LabsSchema = Field(..., description="Pertinent lab results.")
    findings: FindingsSchema = Field(..., description="Physical exam highlights.")

class DrugSchema(BaseModel):
    """
    Schema representing a single medication entry.
    
    Attributes:
        drug (str): The generic name of the medication.
        dose (str, optional): The dosage strength and unit (e.g., '500 mg').
        route (str, optional): The administration route (e.g., 'PO', 'IV', 'SC').
        frequency (str, optional): The frequency of administration (e.g., 'BID', 'Q4H').
    """
    drug: str = Field(..., description="Generic name of the medication.")
    dose: Optional[str] = Field(None, description="Dose with units (e.g., '40 mg').")
    route: Optional[str] = Field(None, description="Route (PO, IV, IM).")
    frequency: Optional[str] = Field(None, description="Frequency (e.g., 'DAILY', 'BID').")


class DeltaSchema(BaseModel):
    """
    Schema for tracking changes in medication regimens (Medication Reconciliation).
    
    Attributes:
        drug (str): Name of the medication being modified.
        change_type (TypeChange): The nature of the change (e.g., NEW_START, STOPPED).
        from_dose (str, optional): The original dose before the change.
        to_dose (str, optional): The new dose after the change.
        reason_inferred (str, optional): Clinical reasoning derived from the text associated with the change.
    """
    drug: str = Field(..., description="Name of the drug changed.")
    change_type: TypeChange = Field(..., description="Nature of the change.")
    from_dose: Optional[str] = Field(None, description="Dose prior to admission/change.")
    to_dose: Optional[str] = Field(None, description="Dose at discharge.")
    reason_inferred: Optional[str] = Field(None, description="Inferred clinical reasoning for the change.")

class TreatmentsSchema(BaseModel):
    """
    Comprehensive schema for medication management and reconciliation.
    
    Attributes:
        admission_drugs (List[DrugSchema]): List of medications the patient was taking prior to admission.
        discharge_drugs (List[DrugSchema]): List of medications prescribed at discharge.
        delta_analysis (List[DeltaSchema]): Structured analysis of changes between admission and discharge medications.
    """
    admission_drugs: List[DrugSchema] = Field(default_factory=list, description="Home meds or meds on arrival.")
    discharge_drugs: List[DrugSchema] = Field(default_factory=list, description="Prescriptions at discharge.")
    delta_analysis: List[DeltaSchema] = Field(default_factory=list, description="Reconciliation of changes.")

class ScribeOutputSchema(BaseModel):
    """
    Master Output Schema for the Scribe Agent.
    This serves as the root structure for all extracted and synthesized clinical data from the TriaLogic pipeline.
    
    Attributes:
        metadata (MetadataSchema): Administrative and classification data.
        semantics (SemanticSchema): High-level clinical summary and context.
        clinical (ClinicalSchema): Structured objective data (vitals, labs, physical exam).
        treatments (TreatmentsSchema): Medication reconciliation and therapy details.
    """
    metadata: MetadataSchema
    semantics: SemanticSchema
    clinical: ClinicalSchema
    treatments: TreatmentsSchema
