
from typing import List, Any, TypedDict, Optional
from src.schemas.scribe_schema import ScribeSchema
from src.schemas.input_schema import InputSchema


class AgentState(TypedDict, total=False):
    """
    Represents the state of the agent throughout the triage and auditing process.
    This TypedDict structure defines the information flow between graph nodes,
    storing input data, extraction results, validation errors, risk assessments,
    context retrieval, and final reports.
    Attributes:
        input (InputSchema): The raw input data for the triage process.
        extracted_data (Optional[ScribeOutputSchema]): The structured and validated JSON data 
            containing vital signs (e.g., SinaisVitais), if extraction was successful.
        validation_error (Optional[str]): Error messages generated by Pydantic validation, 
            if the extraction/validation step fails.
        attempts (int): The current count of attempts for retry loops or logic control.
        risk_score_report (Optional[str]): A compiled report or summary of the calculated 
            risk scores based on the extracted data.
        search_query (Optional[str]): The query string generated to search for relevant context 
            in the knowledge base.
        context_category (Optional[str]): The specific category of medical context retrieved 
            (e.g., protocol type or disease class).
        context_text (Optional[str]): The actual textual content retrieved from the 
            knowledge base to support decision-making.
        auditor_report (Optional[Any]): The final output generated by the auditor, which 
            implementation-wise could be a dictionary or an error message.
    """
 
    input: Optional[InputSchema]              # O input bruto da triagem
    extracted_data: Optional[ScribeSchema] # O JSON validado (SinaisVitais)
    validation_errors: List[Optional[str]]   # Mensagem de erro do Pydantic (se houver)
    validation_messages: List[Any]
    attempts: int
    risk_score_report: Optional[str]  # Resultados dos scores de risco
    search_query: Optional[str]
    context_category: Optional[str]
    context_text: Optional[str]
    auditor_report: Optional[Any]     # Relatório final da auditoria (dict ou msg de erro)
    
    next_step: Optional[str]
    plan: List[str]

    final_report: str