"""
Clinical RAG Agent Module.

This module implements the Clinical Retrieval-Augmented Generation (RAG) node for the TriaLogic agent workflow.
It is responsible for retrieving relevant clinical guidelines, protocols, and medical knowledge based on
the extracted patient data and risk assessment.

Key components:
- `clinical_rag_node`: The main entry point for this agent node.
- `get_vectorstore`: Singleton provider for the ChromaDB vector store connection.
"""

import os
import json
from typing import Dict, Any, cast
from functools import lru_cache
from pydantic import SecretStr
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.messages import SystemMessage, HumanMessage
from dotenv import load_dotenv
import logging

from src.state.agent_state import AgentState

load_dotenv()

# Configuração de Logs (Essencial para TCC e Debug)
logger = logging.getLogger(__name__)

current_dir = os.path.dirname(os.path.abspath(__file__))
# Sobe dois níveis para chegar na raiz do projeto (ajuste conforme sua pasta)
project_root = os.path.dirname(os.path.dirname(current_dir))
# Define o caminho fixo na raiz
PERSIST_DIRECTORY = os.path.join(project_root, "chroma_db")

@lru_cache(maxsize=1)
def get_vectorstore():
    """
    Singleton connection to ChromaDB.

    Returns:
        Chroma: The initialized Chroma vector store instance.
    """
    return Chroma(
        persist_directory=PERSIST_DIRECTORY,
        embedding_function=OpenAIEmbeddings()
    )

# Load prompt with cross-platform path handling
prompt_path = os.path.join(os.getcwd(), "prompts", "rag_prompt.md")
with open(prompt_path, encoding='utf-8') as f:
    QUERY_GEN_SYSTEM = f.read()

def clinical_rag_node(state: AgentState) -> Dict[str, Any]:
    """
    Orchestrates the Clinical RAG (Retrieval-Augmented Generation) process.

    This node performs the following steps:
    1. Recovers extracted patient data and risk assessment from the state.
    2. Generates a targeted search query using an LLM based on patient condition and vitals.
    3. Retrieves relevant clinical guidelines/protocols from the Chroma vector store.
    4. Formats the retrieved context for use by subsequent agents.

    Args:
        state (AgentState): The current state of the agent workflow, containing
                            keys like 'extracted_data', 'risk_score_report', and optionally 'context_category'.

    Returns:
        Dict[str, Any]: A dictionary containing updates to the state:
            - search_query (str): The search query generated by the LLM.
            - context_text (str): The aggregated content of retrieved documents or a fallback message.
    """
    print("--- 🔍 NODE: CLINICAL RAG ---")

    # 1. Recover data from previous nodes
    data = state.get("extracted_data")
    risk = state.get("risk_score_report")

    # 2. Prepare context for query generation
    # Assuming 'data' is an object with 'semantics' and 'clinical' attributes (e.g., Pydantic model)
    patient_summary = json.dumps({
        "condition": data.semantics.chief_complaint if data else "Unknown",
        "vitals": data.clinical.vitals if data else {},
        "risk": risk
    })

    # 3. Query Transformation (LLM)
    llm = ChatOpenAI(
        base_url="http://127.0.0.1:1234/v1",
        api_key=SecretStr("lm-studio"),
        model="gpt-4o-mini",
        temperature=0
    )
    query_msg = [
        SystemMessage(content=QUERY_GEN_SYSTEM),
        HumanMessage(content=f"Patient Data: {patient_summary}")
    ]
    
    # Corrected method from 'invoque' to 'invoke'
    search_query = str(llm.invoke(query_msg).content)

    print(query_msg)
    print(f"[ASSISTANT]: {search_query}")

    # ----------------------------------------
    # SUB-STEP B: RETRIEVAL (RAG)
    # ----------------------------------------
    vectorstore = get_vectorstore()

    # Filter definition
    retriever_kwargs: Dict[str, Any] = {"k": 3}
    context_category = state.get("context_category")
    if context_category:
            retriever_kwargs["filter"] = {"category": context_category}
    docs = vectorstore.similarity_search(search_query, **retriever_kwargs)

    if docs:
        retrieved_context = "\n\n".join([
            f"[Source: {d.metadata.get('source_type', 'Guideline')}]\n{d.page_content}" 
            for d in docs
        ])
        print(f"[RAG]: {retrieved_context}")
    else:
        retrieved_context = "No specific protocol found in the database."
        print("⚠️ [WARNING]: No documents retrieved.")

    return {
        "search_query": search_query,
        "context_text": retrieved_context
    }