import os
import logging
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from dotenv import load_dotenv

from src.state.agent_state import AgentState
from src.utils.vectorstore import get_vectorstore

load_dotenv()

# Logger Configuration
logger = logging.getLogger(__name__)

# --- CONFIGURAÇÃO DE DIRETÓRIOS ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
PERSIST_DIRECTORY = os.path.join(project_root, "chroma_db")

path = os.path.join(project_root, "prompts/rag_prompt.md")
try:
    # Tech Lead Tip: Use caminhos absolutos baseados na raiz do projeto em produção
    full_path = os.path.join(os.getcwd(), path)
    with open(full_path, "r", encoding="utf-8") as f:
        system_prompt = f.read()
except FileNotFoundError:
    logger.error(f"CRITICAL: Prompt file not found at {path}")
    raise RuntimeError(f"Scribe system prompt missing: {path}") 

def clinical_rag_node(state: AgentState) -> AgentState:
    """
    Executes the Clinical RAG (Retrieval-Augmented Generation) node to fetch relevant clinical guidelines.

    This node bridges the gap between raw patient data and established medical knowledge by:
    1.  **Context Extraction**: Pulling patient vitals, risk scores, and a snippet of the clinical note from the agent state.
    2.  **Query Generation**: Using an LLM (Latent Logic Model) to formulated an optimized search query based on the patient's specific condition and the "Constitutional" RAG prompt.
    3.  **Vector Search**: Querying the local ChromaDB vector store to find the top-k most relevant clinical guidelines or protocols.
    4.  **Context formatting**: Formatting the retrieved documents into a concise string for downstream consumption by the Synthesizer agent.

    Args:
        state (AgentState): The current state of the agent, expected to contain 'input' (raw text), 'vitals', and 'risk_score_report'.

    Returns:
        Dict[str, Any]: A dictionary containing state updates:
            - 'search_query': The actual query generated by the LLM.
            - 'rag_context': A concatenated string of retrieved guidelines (or a fallback message if retrieval fails).
    """
    logger.info("🔎🤖--- NODE: CLINICAL RAG ---")
    
    # 1. Inputs Extraction with Expanded Context
    raw_text = state['input'].raw_text[:2000] 
    vitals = state.get("vitals", {})
    risk_score = state.get("risk_score_report", "Risk Score not calculated")
    
    # 2. LLM Configuration (Query Generator)
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0,
        seed=42
    )

    # 3. Prompt Hardcoded (The "Constitution" of RAG)
    user_message = f"""
    PATIENT VITALS: {vitals}
    RISK SCORE: {risk_score}
    
    CLINICAL NOTE SNIPPET (READ CAREFULLY):
    "{raw_text}..."
    
    Generate the optimized search query:
    """

    search_query = "Standard clinical guidelines" # Safe Fallback
    retrieved_context = "Guidelines unavailable due to error."

    try:
        # 4. Query Generation
        logger.debug("Generating Search Query via LLM...")
        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_message)
        ])
        search_query = response.content.strip()
        logger.info(f"🔍 RAG Query Generated: '{search_query}'")

        # 5. Similarity search
        logger.debug("Accessing VectorStore...")
        vectorstore = get_vectorstore()
        docs = vectorstore.similarity_search(search_query, k=3)
        
        if docs:
            formatted_docs = []
            for d in docs:
                source = d.metadata.get('source', 'Guideline')
                content = d.page_content[:600].replace("\n", " ") 
                formatted_docs.append(f"SOURCE [{source}]: {content}...")
            
            retrieved_context = "\n\n".join(formatted_docs)
            logger.info(f"✅ Retrieval Success ({len(docs)} docs found).")
        else:
            logger.warning("⚠️ Retrieval returned 0 documents.")
            retrieved_context = "No specific guidelines found for this query."

    except Exception as e:
        logger.error(f"❌ RAG System Failed: {e}")
        retrieved_context = "CRITICAL: RAG System Offline. Proceed with standard clinical judgment."

    return {
        # "extracted_vitals": vitals,
        "search_query": search_query,
        "rag_context": retrieved_context,
        "rag_context_used": True if retrieved_context else False
    }